version: '2'

services:
  reverse-proxy:
    image: nginx:alpine
    restart: always
    networks:
     - mediaserver-net
    ports:
     - "8080:80"
     # For HTTPs access
     # - "443:443"
    volumes:
     - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     # For HTTPs access
     # - ./conf/nginx/server-cert.pem://etc/ssl/certs/server-cert.pem:ro
     # - ./conf/nginx/server-key.pem://etc/ssl/certs/server-key.pem:ro
     # - ./conf/nginx/dhparam.pem://etc/ssl/certs/dhparam.pem:ro
    links:
     - transmission
     - sonarr
     - couchpotato

  transmission:
    image: linuxserver/transmission
    restart: always
    networks:
     - mediaserver-net
    hostname: transmission
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./conf/transmission/:/config
     - ./media/transmission/downloads/:/downloads
     - ./media/transmission/torrent_files/:/watch

  sonarr:
    image: linuxserver/sonarr
    restart: always
    networks:
     - mediaserver-net
    hostname: sonarr
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
    volumes:
     - /dev/rtc:/dev/rtc:ro
     - ./media/sonarr/series:/tv
     - ./conf/sonarr/:/config
     - ./media/transmission/downloads/:/downloads
    links:
     - transmission

  couchpotato:
    image: linuxserver/couchpotato
    restart: always
    networks:
     - mediaserver-net
    hostname: couchpotato
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./media/couchpotato/movies:/movies
     - ./conf/couchpotato/:/config
     - ./media/transmission/downloads/:/downloads
    links:
     - transmission

networks:
  mediaserver-net:
    driver: bridge
