version: '2'

services:

  transmission:
    image: linuxserver/transmission
    restart: always
    ports:
     - "9091:9091"
     - "51413:51413"
     - "51413:51413/udp"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /home/media/transmission/config/:/config
     - /home/media/transmission/downloads/:/downloads

  sonarr:
    image: linuxserver/sonarr
    restart: always
    ports:
     - "8989:8989"
    volumes:
     - /dev/rtc:/dev/rtc:ro
     - /home/media/sonarr/series:/tv
     - /home/media/sonarr/config:/config
     - /home/media/transmission/downloads/:/downloads
    depends_on:
     - transmission

  couchpotato:
    image: linuxserver/couchpotato
    restart: always
    ports:
     - "5050:5050"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /home/media/couchpotato/movies:/movies
     - /home/media/couchpotato/config/:/config
     - /home/media/transmission/downloads/:/downloads
    depends_on:
     - transmission
