version: '3'

services:
  plex:
    image: plexinc/pms-docker
    networks:
    - web
    ports:
    # DLNA
    - "32469:32469"
    - "1900:1900/udp"
    - "32400:32400"
    environment:
    - PLEX_CLAIM="${PLEX_TOKEN}"
    - ADVERTISE_IP="http://${IP_ADDRESS}:32400/"
    - PLEX_UID="${USER_ID}"
    - PLEX_GID="${GROUP_ID}"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./media/couchpotato/movies:/data/movies
    - ./media/sonarr/series:/data/tvshows
    - ./media/plex/config/:/config
    - /tmp/transcode/:/transcode
    labels:
    - "traefik.backend=plex"
    - "traefik.frontend.rule=Host:plex.${DOMAIN_NAME}"
    - "traefik.port=32400"
    depends_on:
    - transmission
    - sonarr
    - couchpotato

  transmission:
    image: linuxserver/transmission
    networks:
    - web
    ports:
    - "51413:51413"
    - "51413:51413/udp"
    environment:
    - PUID="${USER_ID}"
    - PGID="${GROUP_ID}"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./media/transmission/config/:/config
    - ./media/transmission/downloads/:/downloads
    labels:
    - "traefik.backend=transmission"
    - "traefik.frontend.rule=Host:transmission.${DOMAIN_NAME}"
    - "traefik.port=9091"

  sonarr:
    image: linuxserver/sonarr
    networks:
    - web
    volumes:
    - /dev/rtc:/dev/rtc:ro
    - ./media/sonarr/series:/tv
    - ./media/sonarr/config:/config
    - ./media/transmission/downloads/:/downloads
    environment:
    - PUID="${USER_ID}"
    - PGID="${GROUP_ID}"
    labels:
    - "traefik.backend=sonarr"
    - "traefik.frontend.rule=Host:sonarr.${DOMAIN_NAME}"
    - "traefik.port=8989"
    depends_on:
    - transmission

  couchpotato:
    image: linuxserver/couchpotato
    networks:
    - web
    volumes:
    - /dev/rtc:/dev/rtc:ro
    - ./media/couchpotato/movies:/movies
    - ./media/couchpotato/config/:/config
    - ./media/transmission/downloads/:/downloads
    environment:
    - PUID="${USER_ID}"
    - PGID="${GROUP_ID}"
    labels:
    - "traefik.backend=couchpotato"
    - "traefik.frontend.rule=Host:couchpotato.${DOMAIN_NAME}"
    - "traefik.port=5050"
    depends_on:
    - transmission

  # uncomment to enable torznab as a T411 proxy for couchpotato and sonarr
  # torznab's image will need to be built
  t411proxy:
    build: ../T411-Torznab
    networks:
    - web
    environment:
    - "USERNAME=${T411USERNAME}"
    - "PASSWORD=${T411PASSWORD}"

networks:
  web:
    external:
      name: reverseproxy_default
