version: '2'

services:

  transmission:
    image: linuxserver/transmission
    restart: always
    ports:
     - "9091:9091"
     - "51413:51413"
     - "51413:51413/udp"
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./conf/transmission/:/config
     - ./media/transmission/downloads/:/downloads
     - ./media/transmission/torrent_files/:/watch

  sonarr:
    image: linuxserver/sonarr
    restart: always
    ports:
     - "8989:8989"
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
    volumes:
     - /dev/rtc:/dev/rtc:ro
     - ./media/sonarr/series:/tv
     - ./conf/sonarr/:/config
     - ./media/transmission/downloads/:/downloads
    links:
     - transmission

  couchpotato:
    image: linuxserver/couchpotato
    restart: always
    ports:
     - "5050:5050"
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./media/couchpotato/movies:/movies
     - ./conf/couchpotato/:/config
     - ./media/transmission/downloads/:/downloads
    links:
     - transmission
