version: '2'

services:
  reverse-proxy:
    image: nginx:alpine
    restart: always
    networks:
     - mediaserver-net
    ports:
     - "8080:8080"
     # For HTTPs access
     # - "443:443"
    volumes:
     - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     # For HTTPs access
     # - ./conf/nginx/server-cert.pem://etc/ssl/certs/server-cert.pem:ro
     # - ./conf/nginx/server-key.pem://etc/ssl/certs/server-key.pem:ro
     # - ./conf/nginx/dhparam.pem://etc/ssl/certs/dhparam.pem:ro
    links:
     - transmission
     - sonarr
     - couchpotato
     - plex

  transmission:
    image: linuxserver/transmission
    restart: always
    networks:
     - mediaserver-net
    hostname: transmission
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./conf/transmission/:/config
     - ./media/transmission/downloads/:/downloads
     - ./media/transmission/torrent_files/:/watch

  sonarr:
    image: linuxserver/sonarr
    restart: always
    networks:
     - mediaserver-net
    hostname: sonarr
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
    volumes:
     - /dev/rtc:/dev/rtc:ro
     - ./media/sonarr/series:/tv
     - ./conf/sonarr/:/config
     - ./media/transmission/downloads/:/downloads
    links:
     - transmission

  couchpotato:
    image: linuxserver/couchpotato
    restart: always
    networks:
     - mediaserver-net
    hostname: couchpotato
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./media/couchpotato/movies:/movies
     - ./conf/couchpotato/:/config
     - ./media/transmission/downloads/:/downloads
    links:
     - transmission

  plex:
    image: linuxserver/plex
    restart: always
    networks:
     - mediaserver-net
    hostname: plex
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
     - VERSION=latest
    ports:
     - "32400:32400"
     - "32400:32400/udp"
     - "32469:32469"
     - "32469:32469/udp"
     # We don't require Network discovery on PROD
     # - "5353:5353/udp"
     - "1900:1900/udp"
    volumes:
     - ./media/plex:/config
     - ./media/sonarr/series:/data/tvshows
     - ./media/couchpotato/movies:/data/movies

networks:
  mediaserver-net:
    driver: bridge
